### ISSUE TITLE
module.exports = async

### ISSUE THREAD

**Issue by Qvanstraten** [jonschlinkert/matched#9]
After installing I get the following error.

`..../node_modules/matched/lib/promise.js:8
module.exports = async(patterns, options) => {
                      ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (..../node_modules/matched/lib/async.js:3:14)`

Can you help?

This package was installed automatically as a dependancy of another module.

**Comment by Qvanstraten** [comment]
Node was way behind on this machine... As simple as that.

Thanks for the help!

**Comment by doowb** [comment]
> Thanks for the help!

No problem, I'm glad it's working for you now.
